service: subnextsrv1

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  environment:
    DYNAMODB_TABLE_PREFIX: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_PREFIX}*"

functions:
  mongoms:
    handler: mongomicrosrv.mongoms
    events:
      - http:
          path: v1/{entity}:{id}
          method: get
          cors: true
      - http:
          path: v1/{entity}:{id}
          method: post
          cors: true
      - http:
          path: v1/{entity}
          method: put
          cors: true
      - http:
          path: v1/{entity}:{id}
          method: delete
          cors: true
      - http:
          path: v1/{entity}/q/{filter}
          method: get
          cors: true
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
  microservice:
    handler: handler.microservice
    events:
      - http:
          path: db
          method: get
          cors: true
      - http:
          path: db
          method: options
          cors: true
      - http:
          path: db
          method: post
          cors: true
      - http:
          path: db
          method: delete
          cors: true
      - http:
          path: db
          method: put
          cors: true

resources:
  Resources:
    UserDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE_PREFIX}_user
plugins:
- serverless-offline